name: op-dev-master k2p 
on:
  schedule:
    - cron:  0 20 1 * *
  push:
    branches: master
  

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout - clone repository
      uses: actions/checkout@v2

    - name: Install - system build dependencies
      run: |
        sudo swapoff /swapfile || echo "no swapfile"
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc || echo "clean partly"
        sudo -E apt-get -qq update
        sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync ccache  xsltproc zip
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download - op-dev-master source download
      run: |
        ls -al
        rm -rf op-dev-master
        git clone -b dev-master https://github.com/Lienol/openwrt op-dev-master
        
        
    - name: Update - op-dev-master source update and install 
      run: |
        cd op-dev-master
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a


    - name: Config -  k2p build config
      run: |
        cp .config op-dev-master/

    - name: Download - op-dev-master build dependencies
      run: |
        cd op-dev-master
        make -j8 download V=s

    - name: Build - make lede source
      run: |
        cd op-dev-master
        make -j1 V=s

    - name: Remove - delete packages files
      run: |
        cd op-dev-master/bin/targets/ramips/mt7621/
        rm -rf packages/
        ls -hl

    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: lienol-k2p
        path: op-dev-master/bin/targets/ramips/mt7621/
