name: Lienol k2p 
on:
  schedule:
    - cron:  0 20 1 * *
  push:
    branches: master
  

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout - clone repository
      uses: actions/checkout@v2

    - name: Install - system build dependencies
      run: |
        sudo swapoff /swapfile || echo "no swapfile"
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc || echo "clean partly"
        sudo -E apt-get -qq update
        sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync ccache  xsltproc zip
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download - openwrt source download
      run: |
        ls -al
        rm -rf openwrt
        git clone -b main --single-branch https://github.com/Lienol/openwrt openwrt
        
    - name: Update - openwrt source update and install 1
      run: |
        cd openwrt
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a

      - name: Update - openwrt source update and install 2
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

      - name: Update - openwrt source update and install 3
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Config copy -  k2p build config
      run: |
        cp .config openwrt/
        ls -al
        cd openwrt/
        ls -al

    - name: Download - 下载dl库
      run: |
        cd openwrt
        make -j8 download V=s

    - name: Build - 编译你固件
      run: |
        cd openwrt
        make -j1 V=s


    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: lienol-k2p
        path: openwrt/bin/
